### ISSUE TITLE
Exclude functionality

### ISSUE THREAD

**Issue by cbankston** [mmozuras/pronto-jshint#3]
I'm working with a repository that has checked-in bower packages. Pronto-jshint generates a lot of warnings regarding these 3rd party js files. Because of this, I'm looking for a way to exclude certain paths from being processed by jshintrb or pronto.

I've looked into configuring jshintrb to exclude files and it looks like there is not a way to do this without modifying pronto-jshint to produce/pass a whiltelist of files to pass to jshintrb.

I also notice that other users are requesting this exclude functionality for pronto:
https://github.com/mmozuras/pronto/issues/57

I'd be willing to work on this functionality to fix the problem I am experiencing, as it is kinda painful. Do you have a preference on how/where it should be implemented?

**Comment by mmozuras** [comment]
@cbankston in short, the ideal answer is `.jshintignore` :smile: 

`jshint` itself supports `.jshintignore`. I would start by checking whether `jshintrb` (the Ruby wrapper that `pronto-jshint` uses) supports it too. If it does, just add a note about that to `jshintrb` README and to `pronto-jshint` README. If not, support for it should be added to `jshintrb` and nothing should be changed on `pronto-jshint` side.

**Comment by cbankston** [comment]
@mmozuras the jshintrb project doesn't support the .jshintignore file. Also, it looks like the jshintrb project is dead. Would you be open to a PR that adds exclude functionality to pronto itself?

**Comment by mmozuras** [comment]
@cbankston yes. Configuration file named `.pronto.yml`, copying the way (names, patterns) [rubocop](https://github.com/bbatsov/rubocop) does `.rubocop.yml`.

**Comment by mmozuras** [comment]
@cbankston suggest to continue the conversation on mmozuras/pronto#57. Do tell if you're gonna tackle the configuration file :smile:

**Comment by cbankston** [comment]
@mmozuras sounds great, thanks for your time! I will take care of this the next time I experience the issue. Some other problems came up that I have to tackle first.
