### ISSUE TITLE
Diff is treated as js code?

### ISSUE THREAD

**Issue by spajus** [mmozuras/pronto-jshint#4]
This is the only comment I'm getting from pronto-jshint:

`Bad line breaking before '+'.`

And it is all over the place. I suspect jshint treats diff as js code, and doesn't like + in the beginning.

**Comment by mmozuras** [comment]
@spajus could you try running just `jshint` and see what happens?

> And it is all over the place. I suspect jshint treats diff as js code, and doesn't like + in the beginning.

This is definitely not true :smile: 

Are you sure that your JS is valid? :smile:

**Comment by spajus** [comment]
@mmozuras yeah, with clear head it looks like jshint did the right job (there was badly formatted string), but it failed to put comments in right place. Still, probably not the issue of pronto-jshint itself.
